### ISSUE TITLE
Tables not displaying - Plz help

### ISSUE THREAD

**Issue by ianbill1** [mythirdeye/jtrt-tables#2]
Hi there,

I have used your excellent plugin on our company development site and it worked perfectly, up until 2 days ago. I can see the tables and code for the tables in the back end of the web pages, but they do not display on the live website. Can you please help me out?

**Comment by mythirdeye** [comment]
Hello Ian, 

First of all thank you for using my plugin, and I apologize for the inconvenience,

To get a better understanding of your problem I'm going to ask you a few questions if that's ok.

1) Are you using the 1.3.2 version of this plugin or the new v2? 
1a) If you're using v2, did you upgrade the plugin from the wordpress backend?
1b) if you're using 1.3.2, are you getting any sort of SQL error messages or php error codes on the site?

3 days ago I released version 2.0 for this plugin, unfortunately the Wordpress Plugin Directory is currently buggy and the readme TXT didn't change which means crucial information isn't being displayed. Version 2.0 is completely different from 1.3.2, it adds new features and the plugin core is updated to work better with wordpress. Because of these changes, the wordpress database which contains the tables from the old plugin version needs to be removed otherwise there are errors. To do this, you can simply uninstall the old version, and during uninstall the plugin will remove the tables itself from the database. Then you can download and use v2.0.

If you didn't update to 2.0 and still using the old version of the plugin, I'm going to need a little bit more information to be able to troubleshoot your issue. If you want, to better troubleshoot your issue, you may email me your company website and I will take a look at your live website to see if there are any errors being thrown by the plugin. 

John

**Comment by mythirdeye** [comment]
Hello Ian,

First of all thank you for using my plugin, and I apologize for the inconvenience,

To get a better understanding of your problem I'm going to ask you a few questions if that's ok.

1) Are you using the 1.3.2 version of this plugin or the new v2?
1a) If you're using v2, did you upgrade the plugin from the wordpress backend?
1b) if you're using 1.3.2, are you getting any sort of SQL error messages or php error codes on the site?

3 days ago I released version 2.0 for this plugin, unfortunately the Wordpress Plugin Directory is currently buggy and the readme TXT didn't change which means crucial information isn't being displayed. Version 2.0 is completely different from 1.3.2, it adds new features and the plugin core is updated to work better with wordpress. Because of these changes, the wordpress database which contains the tables from the old plugin version needs to be removed otherwise there are errors. To do this, you can simply uninstall the old version, and during uninstall the plugin will remove the tables itself from the database. Then you can download and use v2.0.

If you didn't update to 2.0 and still using the old version of the plugin, I'm going to need a little bit more information to be able to troubleshoot your issue. If you want, to better troubleshoot your issue, you may email me your company website and I will take a look at your live website to see if there are any errors being thrown by the plugin.

John



________________________________

**Comment by ianbill1** [comment]
Hello John,

Many thanks for coming back to me. Hopefully I can answer your questions and get to the bottom of the disappearing tables! 

Our website is using version 2.0.3 of your plugin.
It was indeed updated within the back-end of WordPress.

What would you suggest I do next? 

Kind regards,
Ian

**Comment by mythirdeye** [comment]
Hello Ian,

 No problem, it's my pleasure :) 

Ok, so this means that you're going to have to delete the current plugin, as in disable the plugin then uninstall it. Unfortunately this will delete your currently saved tables  which is a slight inconvenience :(

Uninstalling the old plugin before updating is required because the new version of the plugin uses a different saving method along with extra information that gets saved. The new version has 2 new breakpoint columns that get stored into the database and because your current tables are still using the old version database, you're going to need to uninstall the plugin. 

Again, unfortunately you're going to have to recreate your tables, however I personally believe its worth it because of the new features, new breakpoints means you can better display your tables on many different browser sizes. 

If you're still having troubles after re-installing, please let me know and I will do my best to further troubleshoot your issue.

Thanks 
John

**Comment by ianbill1** [comment]
Hi John,

This may have proved somewhat annoying at the time but in actual fact, the plugin never saved the tables when I was creating them in the first place. Because of this, I used it to generate HTML code which I saved locally on my PC and then inserted that into each of the pages. 

I have the HTML files and the csv files of each of the pricing tables saved so when I uninstall the plugin by deactivating it and then remove it completely, then re install with the new version, could i use the same HTML code or is there new coding I could put into it to make it work with the new version of the plugin? (Hope that makes sense!)

Kind regards,
Ian

**Comment by mythirdeye** [comment]
Hi Ian,

I'm glad you brought this up. I'm actually not too sure to be completely honest. So you're saying the html code generated by the old version is not working with the new version of the plugin? I don't really see why this wouldn't work but my guess is it could be because the new version of the plugin also uses a new version of footables. This could be causing conflicts with the old html but I'm not really sure why. 

I'm going to setup a test environment and try this out and I will get back to you. In the meantime, did you try re-creating your tables and saving them using the new version of the plugin? If you did a re-install of the new plugin it should be saving correctly, if you can test this out and let me know of your outcome it would help me out a lot. 

Again thanks for bringing this up because it reminded me that I overlooked a pretty important feature in version 2,0 and that is the generate HTML feature. I'm definitely going to re-implement that feature back in during the next update. 

Thanks for your patience and cooperation. I'm going do some bug testing in the test environment if I find the issue I will update you on a fix asap. 

John

**Comment by ianbill1** [comment]
Hi John,

You are correct. We are using the old code generated from the previous version of the plugin with the new version which you released a few days ago. If a fix could be made that enables the old code to work with the new version of the plugin we'd be up and running again. 

I haven't done anything yet with the removal of the plugin. I will hold off for now as we are still adding a load of content to our development site. And being 100% honest, if I can get away with not not recreating 28 new tables I'd be much happier! :-) 

Not a problem. I really appreciate all your help with this so please keep us all updated. I can't be the only one experiencing the issue. 

Many thanks
Ian

**Comment by mythirdeye** [comment]
Hey Ian, 

I think I may have found the issue. Just to clarify, the table headers on your website do show up, but the body content of the table is hidden, correct? 

The new version of the plugin has updated code, it will will only load the scripts required on your website IF there is a jtrt-tables shortcode present within the page. This is so the plugin doesn't attach bulky scripts on pages that don't need it, slowing down the website. The old version of the plugin is actually very poorly coded. The new version is more faster, fluent and interacts much better with wordpress and the website.  

The reason why your tables are not showing correctly is because the new version of the plugin is not loading in the scripts because it doesn't see a jtrt-shortcode within the page. 

I will find a fix for this asap and release an update by the end of the day, in the meantime your best choice of action until the new update is to either (unfortunately) re-create your 28 tables :( or to download version 1.3.2 from github until the update. 

Personally I think it would be worth the effort of re-creating your 28 tables to use with the new version because the new version has many new features such as custom classes for styling, faster code, easier UI, more breakpoints, and a WIP table style editor. I'm still working on the table style editor, its in its baby steps stages but once the ability to fully customize and style your table becomes available, you'd want to be prepared for it :) 

Thanks again for using my plugin and I apologize for the inconvenience the update has caused you. Like I said I will work on an update to better handle custom html generated from the previous version so users in your situation wont have to re-create many tables. 

If you need anything else or having issues in the future please feel free to contact me, I'd be glad to help.

John

**Comment by ianbill1** [comment]
Hi John,

Again, you're correct. The headers show but the table contents are hidden. 

If you're able to include this fix in an update and apply this with future updates, I'm sure a few of us who use the plugin would be very happy. I think you're right in saying that the tables should be updated in line with the new plugin if its of benefit to the end user and website developers. 

I will add the task to my list of things to do but being a dev site, its not the end of the world at the moment. I have a couple of weeks to get things sorted prior to launch. 

All of your improvements sounds great and I look forward to seeing them working. 

No no, thank you for all your help! I thought it would be a long shot messaging you for help on here but you've been most helpful :-) 

All the best and many thanks. 

Kind regards,
Ian

**Comment by mythirdeye** [comment]
Hey Ian,

I just released an update and I thought I should let you know of the current situation. Unfortunately I realized its not possible to use the V1.3.2 generated html tables with the new version of the plugin for one main reason and that is footables. Since footables updated their scripts, they changed a few things around such as the breakpoint hooks. The new footable scripts work differently which is why even if the scripts were to be included on the page, footable wont recognize the old syntax. :(

Ultimately this means that you wont be able to use your old html code with the new plugin version. Your best choice of action would be to either revert back to v1.3.2 or re-create your tables using the new version :( I'm sorry again for the inconvenience, when I was working on the update I guess I wasn't really thinking about the complications of using new technologies :o 

If there's anything else I can help you with please let me know

Best Wishes,
John

**Comment by ianbill1** [comment]
Hi John,

Thanks for coming back to me. 

Would you be able to point me in the right direction for the older version please? V1.3.2

Many thanks. 
Ian

**Comment by ianbill1** [comment]
Hi John,

Excuse my laziness, i found the different versions here - https://wordpress.org/plugins/jtrt-responsive-tables/developers/

Thanks again for all your help and all the best for the future. 

Kind regards
Ian
