### ISSUE TITLE
Hyperlinks in table cell get lost

### ISSUE THREAD

**Issue by brentboylan** [mythirdeye/jtrt-tables#3]
I'm testing out your plugin today because it looked like it would be easier to update my tables with than other plugins I've tried. Unfortunately, about half of my cells have hyperlinks in them that lead to other pages or files and the links are getting stripped out showing only the link name. Is there a way to fix this?

**Comment by mythirdeye** [comment]
Hi Brent, 

I'm assuming this is due to the sanitation. Wordpress database has its own sanitation to make it a little harder for people to do SQL injection attacks on websites. 

I'm going to try to reproduce this problem and I will get back to you with an update soon. 

Thanks
John

**Comment by mythirdeye** [comment]
Hi Brent,

After some fiddling around I found this issue brought up on the FooTables github page. https://github.com/fooplugins/FooTable/issues/355

So it turns out it wasn't wordpress after all that was removing html elements, it was FooTables. 

To solve this issue, you would have to do some html editting. I will include a fix for this in the next update but for now you can solve this by adding the attribute data-type="html" to the column headers of your table. I've created a simple 1 minute video to show you how to achieve this. 
[555555.zip](https://github.com/mythirdeye/jtrt-tables/files/102109/555555.zip)

Let me know if you need anything else, and thanks for trying out my plugin!

John
