### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by dfc9085** [mythirdeye/jtrt-tables#6]
Loving the potential of your plugin!
I am creating a table with some images and while I read that you dont support the images to be responsive, I would expect them to still show up.

They appear in the plugin settings page when I generate the table, but when I put the table in the wordpress page I don't see the images
example here:
http://www.laaviators.com/schedule-2016/

let me know what I might be doing wrong,
thanks!

**Comment by mythirdeye** [comment]
Hi dfc9085,

Sorry for the late response, I've been super busy this week. 

As for your issue, would you mind sending me your CSV file so that I may be able to troubleshoot the issue youre having? My intelligent guess is because the column have to be formatted as html because footable will strip out any html content from the table cells otherwise. If infact this is your issue, you will have to do some html coding to be able to edit your table column data type. This will be fixed with the next update but for now if you could send me a copy of the csv file you're using I'd love to take a closer look at it, 

Thanks for trying out my plugin!
John

**Comment by mythirdeye** [comment]
https://github.com/mythirdeye/jtrt-tables/issues/3 this issue might help with editing your html/etc.

**Comment by dfc9085** [comment]
No worries,
Here is the CSV file,

**Comment by dfc9085** [comment]
adding the data-type "html" fixed it!

thanks!

**Comment by mythirdeye** [comment]
Hey dfc9085, Good to hear that the html attribute was the issue. I will include an update hopefully sometime soon ( ive been very busy ) that will have a way to simply set the data-type for each column from the backend as one would expect.

Thank you again for using my plugin, If you run into anymore issues please feel free to contact me.

**Comment by dfc9085** [comment]
when I resize my browser on my laptop i defintely see the responsive
dropping of columns working,
but when I look at the same page on my phone (iPhone6) its not looking the
same and cropping some of the table off

images attached.

perhaps its my theme not recognizing the mobile device?

thanks for your input

David

**Comment by mythirdeye** [comment]
Hey dfc9085

I'm not seeing any images attached, I didn't get anything in the email either. However from the page you linked earlier I was able to see the problem. I'm not sure why this is happening but when I checked out the html I could tell something was missing. Could I ask which version of the plugin you are using? Did you recently upgrade from v1.32 to v2.x? 

Also I never received the csv file either lol, I don't know if that's an issue with github or if im not looking at the right place but would you mind re-sending me the csv through an email attachment? If I had the csv file to work off of I can better troubleshoot the issue on my test server. 

Thanks
John

**Comment by mythirdeye** [comment]
Hi david, I did some testing on the website that you linked to earlier and as I noticed earlier something with the plugin is going wrong. The old html from the previous plugin is showing up on your table. I'm going to link 2 pictures, the first show the table having 2 sets of initializations and 2 sets of breakpoints. The new version of the plugin uses "breakpoint-xs" and the old version uses "breakpoint-phone". 

You have both showing up on your table which is causing some sort of issue. 
![david issue pic 1](https://cloud.githubusercontent.com/assets/4714913/12978927/f31a85ae-d0a1-11e5-9d41-534d602349cf.jpg)

This is how it looks once I remove the old breakpoints
![david issue pic 2](https://cloud.githubusercontent.com/assets/4714913/12978935/fd41c0ec-d0a1-11e5-9ba1-9181a62c2be8.jpg)


So this lead me to ask a few questions. If you did upgrade to version 2.0 recently, did you delete the previous plugin? "There is no upgrade path from V2 to V3 at present as the options and the way the code is written are inherently different." That quote is from footable. Because my plugin makes use of footable, that means there also isn't an upgrade path from v1.32 to v2 with my plugin. This also means you cannot use tables from the old version with the new version.

John

**Comment by dfc9085** [comment]
here is the CSV file

I think I was mostly using your plugin to generate the inital HTML and then manually editing and styling my table manually. So when I put in on my page Im just using the final HTML and not the shortcode to the  JTRT table...perhaps I messed something up in that translation....
[schedule-csv-4.zip](https://github.com/mythirdeye/jtrt-tables/files/126702/schedule-csv-4.zip)

**Comment by dfc9085** [comment]
I tried making a new table here:
http://www.laaviators.com/__test_schedule/

When I look at the page with chrome developer tools and emulate the iphone 6 it looks correct, 

<img width="397" alt="screen shot 2016-02-11 at 9 34 39 am" src="https://cloud.githubusercontent.com/assets/17093298/12984517/f267936c-d0a2-11e5-9240-63b6c41ac478.png">

but when I look at that page on my actual iPhone 6, it does not 

![img_1237 2](https://cloud.githubusercontent.com/assets/17093298/12984541/15f1de96-d0a3-11e5-903c-8ca9d0cf71e1.PNG)

however..looking closely when the page loads on the phone, it is the correct looking responsive table, with the correct columns dropping out, but then it quickly changes to the image above.

maybe something else in my wordpress site is conflicting

**Comment by mythirdeye** [comment]
Hi David,

Sorry for the delayed response, I had an exam yesterday, then work, so I didnt get a chance to respond.  

As for your issue, on the test website I'm still seeing the same problem with the table being initialized more than once. I know you said you use the plugin to generate the html and then do your own custom work ontop of it so I downloaded your csv file and tried it out on a test server. 

![issue-david](https://cloud.githubusercontent.com/assets/4714913/13029559/75aa0a00-d25d-11e5-8d40-1e8189342ef1.jpg)
Don't mind the massive image, I have triple monitors which is why the picture is huge. If you zoom into the middle and rightmost screens, you can see the difference in the table html on your test page and the table i created on my test server. Other than the fact that my table is missing the pictures, the only difference is the extra classes which are "footable-3" and "breakpoint-phone". 

I still can't get over the breakpoint-phone part. This was the class used in the previous versions of the plugin so I don't know why it would be showing up. Do you have other table plugins that might be  adding an extra footable class to your tables? 

I'm going to do some more testing, if I can find a solution I will be sure to let you know.

Thank
John

**Comment by dfc9085** [comment]
hey John

Thanks for looking into it, and i think i might know where the extra class
is coming from , I had some other plugins for tables i was trying out and i
think they were clobbering and changing things..

I deactivated those plugins, and i think its behaving much better now....
http://www.laaviators.com/__test_schedule/

**Comment by mythirdeye** [comment]
Hey David,

That's good to hear! 

Can I ask for which plugins you had active that were causing the error? I would like to download them and do some testing to ensure that it wont effect other users who may have certain plugins installed. 

Thanks again for proving feedback! It definately helps improve the plugin and its usability. If I find some time (very rare these days) I will work on an update that will solve some of the issues such as having images or href links within the table. In the meantime, If you run into any more issues please feel free to contact me. 

John

**Comment by dfc9085** [comment]
Table Press and the FooTable plugins

**Comment by mythirdeye** [comment]
Hey David,

Thanks for the feedback again! I can already see why the footable plugin might cause issues. I haven't thought of this before but the reason why another class was being added was because both my plugin and footables plugin uses the classname "footable" to generate the specific table. So both plugins are doing what they're supposed to :) This is a fault of my own so I will add this issue to my TOFIX list. 

Thanks again and if you run into any more issues please feel free to contact me!

John
